default:
  image: node:20-alpine

stages:
  - build
  - test

install:
  stage: .pre
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
    policy: pull-push
  script:
    - npm ci --cache .npm --prefer-offline --no-audit 

build:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
    policy: pull
  script:
    - echo "stage build" 
    - npm run build
    - echo "stage build - Done!"
  artifacts:
    paths:
      - dist/    

test:
  stage: test
  dependencies: []
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
    policy: pull
  script:
    - echo "stage test"
    - npm run test
    - echo "stage test - Done!"

lint:
  stage: test
  dependencies: []
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
    policy: pull
  script:
    - echo "stage lint!"
    - npm run lint
    - echo "stage lint - Done!"

stylelint:
  stage: test
  ## шобы не было такого => Downloading artifacts for build (41)..
  dependencies: []
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
      - .npm/
    policy: pull
  script:
    - echo "stage stylelint"
    - npm run stylelint
    - echo "stage stylelint - Done!"

# default:
#   image: node:20-alpine

# stages:
#   - build
#   - test

# cache:
#   - &global_cache_node_mods
#     key:
#       files:
#         - package-lock.json
#     paths:
#       - node_modules/
#     policy: pull

# install:
#   stage: .pre
#   cache:
#     - <<: *global_cache_node_mods
#       when: on_success
#       policy: pull-push
#     - key: ${CI_JOB_NAME}
#       paths:
#         - .npm/
#       when: on_success
#       policy: pull-push 
#   script:
#     - npm ci --cache .npm --prefer-offline --no-audit 

# build:
#   stage: build
#   script:
#     - echo "stage build" 
#     - npm run build
#     - echo "stage build - Done!"
#   artifacts:
#     paths:
#       - dist/    

# test:
#   stage: test
#   script:
#     - echo "stage test"
#     - npm run test
#     - echo "stage test - Done!"


# lint:
#   stage: test
#   script:
#     - echo "stage lint!"
#     - npm run lint
#     - echo "stage lint - Done!"


# stylelint:
#   stage: test
#   script:
#     - echo "stage stylelint"
#     - npm run stylelint
#     - echo "stage stylelint - Done!"    

